name: Build & Release Velopack Installer

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_release:
    name: Build & Release
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Install Velopack CLI (vpk)
        run: dotnet tool install -g vpk

      - name: Extract Branch/Tag Name for Versioning
        id: extract_version
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Pack
        shell: powershell
        run: |
          .\build-installer.ps1 -Version ${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            releases/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
